# Generated by Django 5.1.2 on 2024-10-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
