# Generated by Django 3.2.25 on 2024-11-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_customuser_description_customuser_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
        migrations.AddField(
            model_name='customuser',
            name='NIF',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
