# Generated by Django 3.2.25 on 2024-11-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_auto_20241103_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='NIF',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
