# Generated by Django 3.2.25 on 2024-11-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0004_auto_20241103_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_exist',
            field=models.BooleanField(default=False),
        ),
    ]
