import React from "react";

export const countries = [
    {
      nameES: "España",
      name: "Spain",
      code: "ESP",
      flag: "https://flagcdn.com/es.svg",
      prefix: "+34",
    },
    {
      nameES: "Francia",
      name: "France",
      code: "FRA",
      flag: "https://flagcdn.com/fr.svg",
      prefix: "+33",
    },
    {
      nameES: "Alemania",
      name: "Germany",
      code: "DEU",
      flag: "https://flagcdn.com/de.svg",
      prefix: "+49",
    },
    {
      nameES: "Italia",
      name: "Italy",
      code: "ITA",
      flag: "https://flagcdn.com/it.svg",
      prefix: "+39",
    },
    {
      nameES: "Reino Unido",
      name: "United Kingdom",
      code: "GBR",
      flag: "https://flagcdn.com/gb.svg",
      prefix: "+44",
    },
    {
      nameES: "Portugal",
      name: "Portugal",
      code: "PRT",
      flag: "https://flagcdn.com/pt.svg",
      prefix: "+351",
    },
    {
      nameES: "Países Bajos",
      name: "Netherlands",
      code: "NLD",
      flag: "https://flagcdn.com/nl.svg",
      prefix: "+31",
    },
    {
      nameES: "Suiza",
      name: "Switzerland",
      code: "CHE",
      flag: "https://flagcdn.com/ch.svg",
      prefix: "+41",
    },
    {
      nameES: "Estados Unidos",
      name: "United States",
      code: "USA",
      flag: "https://flagcdn.com/us.svg",
      prefix: "+1",
    },
    {
      nameES: "México",
      name: "Mexico",
      code: "MEX",
      flag: "https://flagcdn.com/mx.svg",
      prefix: "+52",
    },
    {
      nameES: "Argentina",
      name: "Argentina",
      code: "ARG",
      flag: "https://flagcdn.com/ar.svg",
      prefix: "+54",
    },
    {
      nameES: "Brasil",
      name: "Brazil",
      code: "BRA",
      flag: "https://flagcdn.com/br.svg",
      prefix: "+55",
    },
    {
      nameES: "Chile",
      name: "Chile",
      code: "CHL",
      flag: "https://flagcdn.com/cl.svg",
      prefix: "+56",
    },
    {
      nameES: "Colombia",
      name: "Colombia",
      code: "COL",
      flag: "https://flagcdn.com/co.svg",
      prefix: "+57",
    },
    {
      nameES: "Perú",
      name: "Peru",
      code: "PER",
      flag: "https://flagcdn.com/pe.svg",
      prefix: "+51",
    },
    {
      nameES: "Canadá",
      name: "Canada",
      code: "CAN",
      flag: "https://flagcdn.com/ca.svg",
      prefix: "+1",
    },
    {
      nameES: "Japón",
      name: "Japan",
      code: "JPN",
      flag: "https://flagcdn.com/jp.svg",
      prefix: "+81",
    },
    {
      nameES: "China",
      name: "China",
      code: "CHN",
      flag: "https://flagcdn.com/cn.svg",
      prefix: "+86",
    },
    {
      nameES: "India",
      name: "India",
      code: "IND",
      flag: "https://flagcdn.com/in.svg",
      prefix: "+91",
    },
    {
      nameES: "Corea del Sur",
      name: "South Korea",
      code: "KOR",
      flag: "https://flagcdn.com/kr.svg",
      prefix: "+82",
    },
    {
      nameES: "Indonesia",
      name: "Indonesia",
      code: "IDN",
      flag: "https://flagcdn.com/id.svg",
      prefix: "+62",
    },
    {
      nameES: "Vietnam",
      name: "Vietnam",
      code: "VNM",
      flag: "https://flagcdn.com/vn.svg",
      prefix: "+84",
    },
    {
      nameES: "Sudáfrica",
      name: "South Africa",
      code: "ZAF",
      flag: "https://flagcdn.com/za.svg",
      prefix: "+27",
    },
    {
      nameES: "Egipto",
      name: "Egypt",
      code: "EGY",
      flag: "https://flagcdn.com/eg.svg",
      prefix: "+20",
    },
    {
      nameES: "Nigeria",
      name: "Nigeria",
      code: "NGA",
      flag: "https://flagcdn.com/ng.svg",
      prefix: "+234",
    },
    {
      nameES: "Kenia",
      name: "Kenya",
      code: "KEN",
      flag: "https://flagcdn.com/ke.svg",
      prefix: "+254",
    },
    {
      nameES: "Marruecos",
      name: "Morocco",
      code: "MAR",
      flag: "https://flagcdn.com/ma.svg",
      prefix: "+212",
    },
    {
      nameES: "Australia",
      name: "Australia",
      code: "AUS",
      flag: "https://flagcdn.com/au.svg",
      prefix: "+61",
    },
    {
      nameES: "Nueva Zelanda",
      name: "New Zealand",
      code: "NZL",
      flag: "https://flagcdn.com/nz.svg",
      prefix: "+64",
    },
    {
      nameES: "Fiyi",
      name: "Fiji",
      code: "FJI",
      flag: "https://flagcdn.com/fj.svg",
      prefix: "+679",
    },
  ];